import type { Metadata } from "next";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import localFont from 'next/font/local';
import { Providers } from "./provider";
import MainLayout from "@/app/components/MainLayout/mainLayout";

// laptop 1440x900
// mobile 375x667

const proFontWindows = localFont({
  src:[
    {
      path:'../../public/fonts/ProFontWindows.ttf',
      weight:"400",
    },
  ],
  variable:"--font-proFont",
},
);

const qanelas = localFont({
  src:[
    {
      path:'../../public/fonts/qanelas/QanelasRegular.otf',
      weight:"400",
    },
  ],
    variable:"--font-qanelas",
});

export const metadata: Metadata = {
  title: "FamProtocol",
  description: "Generated by create next app",
};



export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en" className={`${proFontWindows.variable} ${qanelas.variable}`} >
      <head>
        <meta charSet="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="https://clusterprotocol2024.s3.amazonaws.com/website+logo/logo.png" sizes="any" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Krub:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&family=New+Amsterdam&display=swap" rel="stylesheet"></link>
      </head>
      <body>
        <Providers>
        <MainLayout>
        { children }
        </MainLayout>
        </Providers>
      </body>
    </html>
  );
}
